### ISSUE TITLE
Trying to install

### ISSUE THREAD

**Issue by tyeeman** [fazalmajid/pswp#2]
I'm running 
```
go install github.com/fazalmajid/pswp@latest
```
and I get this error - 
```
pkg\mod\github.com\fazalmajid\pswp@v0.0.0-20231130221958-343a35089b7b\pswp.go:57:12: pattern PhotoSw
ipe/dist/*.js: no matching files found
```
Line 57 is this - 
```
//go:embed PhotoSwipe/dist/*.js
```
which is a comment so what am I doing wrong? I'm on windows so I can't use the makefile.

Update - I downloaded Photoswipe repo and copied the "dist" folder into a "Photoswipe" folder and then ran locally
```
go build pswp.go
```
and I now have the exe. Sounds good, yes?

**Comment by tyeeman** [comment]
Running the command I get this error - 
```
d:\4>pswp -t "Photos" -o "out" *.jpg
2023/12/14 22:50:53 could not stat*.jpg: CreateFile *.jpg: The filename, directory name, or volume l
abel syntax is incorrect.
```
Anything come to mind? Where are the jpg images supposed to be located?

**Comment by fazalmajid** [comment]
Yes, you need to run make so it can fetch the PhotoSwipe JavaScript assets that will be embedded into the executable.

As for the error you are seeing, it’s because of how Windows’ cmd.exe differs from the UNIX shell in handling wildcards. The UNIX shell does the expansion so the program would see:

```
pswp -t Photos -o out photo1.jpg photo2.jpg photo3.jpg …
```

whereas on Windows it will literally get `*.jpg` and there is no file named that, hence the error. MS-DOS and Windows command-line programs are expected to do the globbing expansion themselves.

~~I don’t know if PowerShell behaves like a proper shell, you could try it,~~ or build on WSL2, otherwise I’d have to implement globbing on Windows.

**Comment by tyeeman** [comment]
I should be able to make a batch file do it. I'll try tonight. Thanks.

**Comment by fazalmajid** [comment]
OK, so I added the globbing support and also removed a dependency on Info-Zip zip which is not installed by default on Windows. I don't have a Go toolchain or make on Windows, so I cross-compiled (`env GOOS=windows GOARCH=amd64 gmake clean all`) on my Mac, the resulting executable works on my Windows ~~game console~~ test machine. Let me know if you have any issues after rebuilding.

**Comment by fazalmajid** [comment]
I also added a GitHub action to automatically build `pswp.exe` for Windows on each release.

**Comment by tyeeman** [comment]
Great, works perfect! Thanks.

Update - One bug seems to be if I run the build again I get this error - 
```
D:\4>pswp -t "Photos" -o "out" *.jpg
2023/12/15 21:12:25 could not copy assets:open out\photoswipe-lightbox.esm.js: Access is denied.
```
I have to delete all the files in the "out" folder to have a successful build again.

Maybe add a command line option for no download of all images in zip file.

I guess photoswipe does not have an option for multiple galleries?
